#! /usr/bin/env sh
set -e

DEFAULT_MODULE_NAME=${DEFAULT_MODULE_NAME:-"main"}
DEFAULT_GUNICORN_CONF=${DEFAULT_GUNICORN_CONF:-"/code/gunicorn_conf.py"}

MODULE_NAME=${MODULE_NAME:-$DEFAULT_MODULE_NAME}
VARIABLE_NAME=${VARIABLE_NAME:-app}
export APP_MODULE=${APP_MODULE:-"$MODULE_NAME:$VARIABLE_NAME"}

export GUNICORN_CONF=${GUNICORN_CONF:-$DEFAULT_GUNICORN_CONF}
export WORKER_CLASS=${WORKER_CLASS:-"uvicorn.workers.UvicornWorker"}
export FORWARDED_ALLOW_IPS="*"

# Start Gunicorn
exec gunicorn -k "$WORKER_CLASS" -c "$GUNICORN_CONF" "$APP_MODULE"
